/* UIFY — generated by cbindgen. DO NOT EDIT. */

#ifndef UIFY_H
#define UIFY_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Placeholder.
 */
uint32_t uify_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UIFY_H */
